const userTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",

  SIGN_IN_EMAIL: "SIGN_IN_EMAIL",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",

  START_SIGN_UP: "START_SIGN_UP",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
}
export default userTypes
